FROM owncloudci/nodejs:16@sha256:96f3458b066c3caa67860352ca7d45054c60c76ee76a7f2ae843330fd5e3d408

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Transifex"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/transifex"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/transifex"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/transifex"

ARG BUILD_VERSION

# renovate: datasource=github-releases depName=transifex/cli
ENV TRANSIFEX_VERSION="${BUILD_VERSION:-1.6.4}"

RUN apt-get update && \
    apt-get install -y git-core perl gettext liblocale-po-perl liblocale-gettext-perl && \
    curl -SsfL "https://github.com/transifex/cli/releases/download/v${TRANSIFEX_VERSION}/tx-linux-amd64.tar.gz" | tar xz -C /usr/local/bin tx && \
    npm install -g yarn --force && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rootfs /

ENTRYPOINT ["/usr/local/bin/tx"]
