FROM owncloudci/nodejs:12@sha256:c8556a24f9ff536b11669e5dc4cba39d70b8a759378d307c15ab432d9d913589

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Transifex"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/transifex"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/transifex"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/transifex"

ARG BUILD_VERSION

# renovate: datasource=pypi depName=transifex-client
ENV TRANSIFEX_VERSION="${BUILD_VERSION:-0.14.2}"

RUN apt-get update && \
    apt-get install -y git-core perl gettext liblocale-po-perl liblocale-gettext-perl python3 python3-pip && \
    pip3 install -U "transifex-client==$TRANSIFEX_VERSION" && \
    npm install -g yarn --force && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rootfs /

ENTRYPOINT ["/usr/local/bin/tx"]
